3# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    git submodule update --init --recursive
    mkdir build
    cd build
    cmake ..
    cmake --build . --config Release
    cd test
    ctest -VV
  displayName: 'cmake test'
