# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

# https://github.com/Azure/azure-storage-cpplite  
- script: |
    git clone https://github.com/curl/curl.git -b curl-7_65_0 
    git clone https://github.com/openssl/openssl.git -b OpenSSL_1_1_1b
    .\curl\projects\build-openssl.bat vc14.1 x64 debug .\openssl\ -perlpath C:\Strawberry
  displayName: 'install openssl'

- script: |
    git submodule update --init --recursive
    mkdir build
    cd build
    cmake -DMQTT_NO_TLS=OFF -DMQTT_USE_WS=OFF  -DMQTT_USE_STR_CHECK=OFF   -DMQTT_TEST_1=ON  -DMQTT_TEST_2=OFF -DMQTT_TEST_3=OFF -DBUILD_EXAMPLES=OFF ..
    cmake --build . --config Release
    cd test
    echo "---"
    set
    echo "---"
    set PATH=%BOOST_ROOT%\lib;%PATH%
    echo "---"
    set
    echo "---"
    ctest -VV
  displayName: 'cmake test'
